/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 4"
  https://create.arduino.cc/cloud/things/ef7df603-7eb0-4491-979c-dcdb57bd3ac0 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int servo_angle_00;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// https://github.com/arduino-libraries/Servo
#include <Servo.h>
#define SERVO_PIN 21
Servo servo;


void setup() 
{
  // Generated code
  Serial.begin(9600);
  delay(1500); 
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  servo_angle_00 = 0;
  servo.attach( SERVO_PIN );
  
}


void loop() 
{
  ArduinoCloud.update();
  // Your code here 
}


/*
  Since ServoAngle00 is READ_WRITE variable, onServoAngle00Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onServoAngle00Change()  
{
  // Add your code here to act upon ServoAngle00 change
  
  // https://www.handsontec.com/dataspecs/motor_fan/MG996R.pdf
  // "This high-torque standard servo can rotate approximately 120º"
  // -60 on the dashboard (slider left side) maps to: 120
  //   0 on the dashboard (middle of slider) maps to:  60
  //  60 on the dashboard (slider right side) maps to:  0
  servo.write( ( -1 ) * ( servo_angle_00 - 60 ) );
  
}

